name: persian_datetimepickers_example
description: A valuable and straightforward package that supports Jalali(Farsi | Persian) and the gregorian date and time pickers and converters.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  persian_datetimepickers:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
    

flutter:
  uses-material-design: true